use_frameworks!

platform :ios, '8.0'

target 'CCBRKSegmentedControl_Example' do
  pod 'CCBRKSegmentedControl', :path => '../'

  target 'CCBRKSegmentedControl_Tests' do
    inherit! :search_paths

    
  end
end
